"""`shorts clean`: delete output/temp (everything in it is regenerated by re-running the steps that made it).

Never touches output/final (the deliverables), output/jobs (footage copies, transcripts, edit decisions), films/ or kit/.
"""
from __future__ import annotations

import shutil
from pathlib import Path

from shorts import config
from shorts.errors import ShortsError


def _size(p: Path) -> int:
    if p.is_file():
        return p.stat().st_size
    return sum(f.stat().st_size for f in p.rglob("*") if f.is_file() and not f.is_symlink())


def _mb(n: int) -> float:
    return round(n / 1e6, 1)


def clean(targets: list[str], dry_run: bool = False) -> dict:
    """targets: [] for all of output/temp, else names under it ('jobs/<take>', 'films/<video>', 'cache', a take name)."""
    temp = config.TEMP.resolve()
    if not temp.exists():
        return {"deleted": [], "freed_mb": 0.0, "dry_run": dry_run, "note": f"{temp} is already empty"}
    if targets:
        paths = []
        for t in targets:
            cand = [temp / t] if "/" in t or t == "cache" else [temp / "jobs" / t, temp / "films" / t]
            hits = [p for p in cand if p.exists()]
            if not hits:
                raise ShortsError("E_NOTHING_TO_CLEAN", f"Nothing named {t!r} in {temp}.",
                                  "List it: ls output/temp/jobs output/temp/films")
            paths += hits
    else:
        paths = sorted(temp.iterdir())
    for p in paths:          # a target can never reach outside output/temp ("../jobs", a symlink out)
        if not p.resolve().is_relative_to(temp) or (targets and p.resolve() == temp):
            raise ShortsError("E_NOT_TEMP", f"{p} is not inside output/temp.",
                              "Only output/temp can be cleaned: name a take, a film, 'cache', or nothing for all of it.")
    report = [{"path": "output/" + str(p.relative_to(temp.parent)), "mb": _mb(_size(p))} for p in paths]
    if not dry_run:
        for p in paths:
            if p.is_dir() and not p.is_symlink():
                shutil.rmtree(p)
            else:
                p.unlink(missing_ok=True)
    return {"deleted" if not dry_run else "would_delete": report, "freed_mb": round(sum(r["mb"] for r in report), 1),
            "dry_run": dry_run,
            "kept": ["output/final (deliverables)", "output/jobs (footage, transcripts, decisions)"]}


def add_command(sub) -> None:
    p = sub.add_parser("clean", help="Delete output/temp (all regenerable). Deliverables, takes and decisions are kept.")
    p.add_argument("targets", nargs="*", help="only these: a take or film name, 'jobs/<take>', 'films/<video>' or 'cache'")
    p.add_argument("--dry-run", action="store_true", help="list what would be deleted and its size")
    p.set_defaults(func=lambda a: clean(a.targets, a.dry_run))
